version: '3.8'
services:
  jenkins:
    image: myjenkins-arm64
    container_name: jenkins
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JENKINS_URL=https://localhost:8081/
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: